[versions]
# Libraries
activityCompose = "1.12.4"
androidxHilt = "1.3.0"
composeUiTestManifest = "1.10.3"
coreKtx = "1.17.0"
desugarJdkLibsNio = "2.1.5"
espressoCore = "3.7.0"
junit = "4.13.2"
junitVersion = "1.3.0"
lifecycleRuntimeKtx = "2.10.0"

# BOMs
composeBom = "2026.02.00"

# Plugins
androidApplication = "9.0.1"
hilt = "2.59.1"
kotlinCompose = "2.3.10"
ksp = "2.3.4"

[libraries]
androidxActivityCompose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidxComposeUiTestManifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "composeUiTestManifest" }
androidxCoreKtx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
androidxEspressoCore = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
androidxJunit = { module = "androidx.test.ext:junit", version.ref = "junitVersion" }
androidxLifecycleRuntimeKtx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
desugarJdkLibsNio = { module = "com.android.tools:desugar_jdk_libs_nio", version.ref = "desugarJdkLibsNio" }
hiltAndroid = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hiltAndroidCompilerKsp = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
hiltAndroidxNavigationCompose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "androidxHilt" }
junit = { module = "junit:junit", version.ref = "junit" }

# Compose BOM
composeBom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
composeMaterial3 = { module = "androidx.compose.material3:material3" }
composeUi = { module = "androidx.compose.ui:ui" }
composeUiGraphics = { module = "androidx.compose.ui:ui-graphics" }
composeUiTestJunit4 = { module = "androidx.compose.ui:ui-test-junit4" }
composeUiTooling = { module = "androidx.compose.ui:ui-tooling" }
composeUiToolingPreview = { module = "androidx.compose.ui:ui-tooling-preview" }

[plugins]
androidApplicationPlugin = { id = "com.android.application", version.ref = "androidApplication" }
hiltAndroidPlugin = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlinComposePlugin = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlinCompose" }
kspPlugin = { id = "com.google.devtools.ksp", version.ref = "ksp" }

[bundles]
composeBomRuntime = [
    "composeMaterial3",
    "composeUi",
    "composeUiGraphics",
    "composeUiToolingPreview",
]

hiltRuntime = [
    "hiltAndroid",
    "hiltAndroidxNavigationCompose"
]
