[versions]
# Library versions
accompanistPermissionsVersion = "0.37.3"
activityComposeVersion = "1.12.4"
androidxJunitVersion = "1.3.0"
coreKtxVersion = "1.17.0"
desugarVersion = "2.1.5"
espressoCoreVersion = "3.7.0"
junitVersion = "4.13.2"
lifecycleVersion = "2.10.0"
timberVersion = "5.0.1"
uiTestManifestVersion = "1.10.4"
workVersion = "2.11.1"

# Plugin versions
androidApplicationPluginVersion = "9.0.1"
kotlinComposePluginVersion = "2.3.10"
kspPluginVersion = "2.3.4"

# Versions common across two or more of lib, plugin, and ksp
androidxHiltCommonVersion = "1.3.0"
hiltCommonVersion = "2.59.2"

# BOM versions
composeBomVersion = "2026.02.01"

[libraries]
accompanistPermissionsLib = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanistPermissionsVersion" }
activityComposeLib = { module = "androidx.activity:activity-compose", version.ref = "activityComposeVersion" }
androidxJunitLib = { module = "androidx.test.ext:junit", version.ref = "androidxJunitVersion" }
coreKtxLib = { module = "androidx.core:core-ktx", version.ref = "coreKtxVersion" }
desugarLib = { module = "com.android.tools:desugar_jdk_libs_nio", version.ref = "desugarVersion" }
espressoCoreLib = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCoreVersion" }
hiltAndroidCompilerKspLib = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hiltCommonVersion" }
hiltAndroidLib = { module = "com.google.dagger:hilt-android", version.ref = "hiltCommonVersion" }
hiltCompilerKspLib = { module = "androidx.hilt:hilt-compiler", version.ref = "androidxHiltCommonVersion" }
hiltNavigationComposeLib = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "androidxHiltCommonVersion" }
hiltWorkLib = { module = "androidx.hilt:hilt-work", version.ref = "androidxHiltCommonVersion" }
junitLib = { module = "junit:junit", version.ref = "junitVersion" }
lifecycleLib = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleVersion" }
timberLib = { module = "com.jakewharton.timber:timber", version.ref = "timberVersion" }
uiTestManifestLib = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "uiTestManifestVersion" }
workLib = { module = "androidx.work:work-runtime-ktx", version.ref = "workVersion" }

# Compose BOM libraries
composeBomLib = { module = "androidx.compose:compose-bom", version.ref = "composeBomVersion" }
material3Lib = { module = "androidx.compose.material3:material3" }
uiGraphicsLib = { module = "androidx.compose.ui:ui-graphics" }
uiLib = { module = "androidx.compose.ui:ui" }
uiTestJunit4Lib = { module = "androidx.compose.ui:ui-test-junit4" }
uiToolingLib = { module = "androidx.compose.ui:ui-tooling" }
uiToolingPreviewLib = { module = "androidx.compose.ui:ui-tooling-preview" }

[plugins]
androidApplicationPlugin = { id = "com.android.application", version.ref = "androidApplicationPluginVersion" }
hiltAndroidPlugin = { id = "com.google.dagger.hilt.android", version.ref = "hiltCommonVersion" }
kotlinComposePlugin = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlinComposePluginVersion" }
kspPlugin = { id = "com.google.devtools.ksp", version.ref = "kspPluginVersion" }

[bundles]
composeBomRuntime = [
    "material3Lib",
    "uiGraphicsLib",
    "uiLib",
    "uiToolingPreviewLib",
]

hiltRuntime = [
    "hiltAndroidLib",
    "hiltNavigationComposeLib",
    "hiltWorkLib",
]

hiltKsp = [
    "hiltAndroidCompilerKspLib",
    "hiltCompilerKspLib",
]
