[versions]
# Libraries
activityComposeVersion = "1.12.4"
androidxWorkVersion = "2.11.1"
composeUiTestManifestVersion = "1.10.3"
coreKtxVersion = "1.17.0"
desugarJdkLibsNioVersion = "2.1.5"
espressoCoreVersion = "3.7.0"
junitVersion = "4.13.2"
androidxJunitVersion = "1.3.0"
lifecycleRuntimeKtxVersion = "2.10.0"
timberVersion = "5.0.1"

# BOMs
composeBomVersion = "2026.02.00"

# Plugins
androidApplicationPluginVersion = "9.0.1"
kotlinComposePluginVersion = "2.3.10"
kspPluginVersion = "2.3.4"

# Common across two or more of lib, plugin, and ksp
androidxHiltCommonVersion = "1.3.0"
hiltCommonVersion = "2.59.2"

[libraries]
androidxActivityCompose = { module = "androidx.activity:activity-compose", version.ref = "activityComposeVersion" }
androidxComposeUiTestManifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "composeUiTestManifestVersion" }
androidxCoreKtx = { module = "androidx.core:core-ktx", version.ref = "coreKtxVersion" }
androidxEspressoCore = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCoreVersion" }
androidxJunit = { module = "androidx.test.ext:junit", version.ref = "androidxJunitVersion" }
androidxLifecycleRuntimeKtx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtxVersion" }
androidxHiltWork = { module = "androidx.hilt:hilt-work", version.ref = "androidxHiltCommonVersion" }
androidxWorkRuntime = { module = "androidx.work:work-runtime-ktx", version.ref = "androidxWorkVersion" }
desugarJdkLibsNio = { module = "com.android.tools:desugar_jdk_libs_nio", version.ref = "desugarJdkLibsNioVersion" }
hiltAndroid = { module = "com.google.dagger:hilt-android", version.ref = "hiltCommonVersion" }
hiltAndroidCompilerKsp = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hiltCommonVersion" }
hiltAndroidxNavigationCompose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "androidxHiltCommonVersion" }
hiltCompilerKsp = { module = "androidx.hilt:hilt-compiler", version.ref = "androidxHiltCommonVersion" }
junit = { module = "junit:junit", version.ref = "junitVersion" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timberVersion" }

# Compose BOM
composeBom = { module = "androidx.compose:compose-bom", version.ref = "composeBomVersion" }
composeMaterial3 = { module = "androidx.compose.material3:material3" }
composeUi = { module = "androidx.compose.ui:ui" }
composeUiGraphics = { module = "androidx.compose.ui:ui-graphics" }
composeUiTestJunit4 = { module = "androidx.compose.ui:ui-test-junit4" }
composeUiTooling = { module = "androidx.compose.ui:ui-tooling" }
composeUiToolingPreview = { module = "androidx.compose.ui:ui-tooling-preview" }

[plugins]
androidApplicationPlugin = { id = "com.android.application", version.ref = "androidApplicationPluginVersion" }
hiltAndroidPlugin = { id = "com.google.dagger.hilt.android", version.ref = "hiltCommonVersion" }
kotlinComposePlugin = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlinComposePluginVersion" }
kspPlugin = { id = "com.google.devtools.ksp", version.ref = "kspPluginVersion" }

[bundles]
composeBomRuntime = [
    "composeMaterial3",
    "composeUi",
    "composeUiGraphics",
    "composeUiToolingPreview",
]

hiltRuntime = [
    "androidxHiltWork",
    "hiltAndroid",
    "hiltAndroidxNavigationCompose"
]

hiltKsp = [
    "hiltAndroidCompilerKsp",
    "hiltCompilerKsp"
]
